FROM node:18-alpine

ARG CLIENT_PORT
ENV CLIENT_PORT ${CLIENT_PORT}

WORKDIR /app
COPY ./package.json .
COPY ./yarn.lock .
COPY ./next.config.mjs .
COPY ./postcss.config.mjs .
COPY ./tailwind.config.ts .
COPY ./tsconfig.json .
RUN yarn
CMD yarn dev -p ${CLIENT_PORT}

