FROM node:22-alpine

ARG CLIENT_PORT
ENV CLIENT_PORT=${CLIENT_PORT}

ARG SERVER_HOST
ENV SERVER_HOST=${SERVER_HOST}

ARG SERVER_PROTOCOL
ENV SERVER_PROTOCOL=${SERVER_PROTOCOL}

WORKDIR /app
COPY ./package.json .
COPY ./yarn.lock .
COPY ./next.config.mjs .
COPY ./postcss.config.mjs .
COPY ./tailwind.config.ts .
COPY ./tsconfig.json .
RUN yarn
CMD yarn dev -p ${CLIENT_PORT}