networks:
  internal:
    external: false
services:
  data:
    build:
      context: db
      dockerfile: Dockerfile
    volumes:
      - ./db:/db
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT:-5432}
      DATA_PASSWORD: /run/secrets/db_secret
    secrets:
      - db_secret
  db:
    image: postgres
    restart: always
    depends_on:
      data:
        condition: service_completed_successfully
    environment:
      POSTGRES_USER: transport
      POSTGRES_DB: transport
      POSTGRES_PASSWORD: transport
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/.populate/:/docker-entrypoint-initdb.d/
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 1s
      retries: 500
      start_period: 0s
  adminer:
    image: adminer
    depends_on:
      db:
        condition: service_healthy
    restart: always
    ports:
      - 8085:8080
    networks:
      - internal
  watcher:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: db/watcher
      dockerfile: Dockerfile
      args:
        POETRY_VERSION: 2.1.1
    environment:
      DB_HOST: db
      DB_USER: transport
      DB_NAME: transport
      DB_PASSWORD: /run/secrets/db_secret
    volumes:
      - ./db/code:/app/code
    networks:
      - internal
  api:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: api
      dockerfile: Dockerfile.dev
      args:
        POETRY_VERSION: 2.1.1
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      API_ENV: dev
      API_PORT: ${API_PORT}
      DATA_DIR: ${DATA_DIR}
      RTT_USER: ${RTT_USER}
      RTT_PASSWORD: /run/secrets/rtt_secret
      NATRAIL_USER: ${NATRAIL_USER}
      NATRAIL_PASSWORD: /run/secrets/natrail_secret
      DB_HOST: db
      DB_USER: transport
      DB_PASSWORD: /run/secrets/db_secret
      DB_NAME: transport
      TIMEZONE: ${TIMEZONE}
      NETWORK_PATH: /app/data/${NETWORK_FILE}
    volumes:
      - ./api/src:/app/src
      - ./api/data:/app/data
    secrets:
      - rtt_secret
      - natrail_secret
    networks:
      - internal
    healthcheck:
      test:
        ["CMD-SHELL", "curl --fail http://localhost:$$API_PORT/hc || exit 1"]
      interval: 10s
      timeout: 1s
      retries: 100
      start_period: 0s
  client:
    depends_on:
      api:
        condition: service_healthy
    build:
      context: client
      dockerfile: Dockerfile.dev
      args:
        CLIENT_PORT: ${CLIENT_PORT}
        SERVER_HOST: api:${API_PORT}
        SERVER_PROTOCOL: http
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    environment:
      API_URL: "http://api:${API_PORT}"
      CLIENT_PORT: ${CLIENT_PORT}
      NEXT_PUBLIC_MAPTILER_KEY: ${MAPTILER_KEY}
    volumes:
      - ./client/src:/app/src
    networks:
      - internal
secrets:
  rtt_secret:
    file: rtt.secret
  db_secret:
    file: db.secret
  natrail_secret:
    file: natrail.secret
volumes:
  pgdata:
