DROP DOMAIN IF EXISTS TEXT_NOTNULL;
DROP DOMAIN IF EXISTS INTEGER_NOTNULL;
DROP DOMAIN IF EXISTS DECIMAL_NOTNULL;
DROP DOMAIN IF EXISTS TIMESTAMP_NOTNULL;
DROP DOMAIN IF EXISTS INTERVAL_NOTNULL;
DROP DOMAIN IF EXISTS DATERANGE_NOTNULL;
DROP DOMAIN IF EXISTS BOOLEAN_NOTNULL;

CREATE DOMAIN TEXT_NOTNULL AS TEXT NOT NULL;
CREATE DOMAIN INTEGER_NOTNULL AS INTEGER NOT NULL;
CREATE DOMAIN DECIMAL_NOTNULL AS DECIMAL NOT NULL;
CREATE DOMAIN TIMESTAMP_NOTNULL AS TIMESTAMP WITH TIME ZONE NOT NULL;
CREATE DOMAIN INTERVAL_NOTNULL AS INTERVAL NOT NULL;
CREATE DOMAIN DATERANGE_NOTNULL AS DATERANGE NOT NULL;
CREATE DOMAIN BOOLEAN_NOTNULL AS BOOLEAN NOT NULL;