DROP DOMAIN TEXT_NOTNULL;
DROP DOMAIN INTEGER_NOTNULL;
DROP DOMAIN DECIMAL_NOTNULL;
DROP DOMAIN TIMESTAMP_NOTNULL;
DROP DOMAIN INTERVAL_NOTNULL;
DROP DOMAIN DATERANGE_NOTNULL;

CREATE DOMAIN TEXT_NOTNULL AS TEXT NOT NULL;
CREATE DOMAIN INTEGER_NOTNULL AS INTEGER NOT NULL;
CREATE DOMAIN DECIMAL_NOTNULL AS DECIMAL NOT NULL;
CREATE DOMAIN TIMESTAMP_NOTULL AS TIMESTAMP WITH TIME ZONE NOT NULL;
CREATE DOMAIN INTERVAL_NOTNULL AS INTERVAL NOT NULL;
CREATE DOMAIN DATERANGE_NOTNULL AS DATERANGE NOT NULL;