# Build image
FROM python:3.13-bookworm AS builder

RUN apt update
RUN apt install firefox-esr -y

RUN curl -L -O https://github.com/mozilla/geckodriver/releases/download/v0.36.0/geckodriver-v0.36.0-linux64.tar.gz
RUN tar -zxvf geckodriver-v0.36.0-linux64.tar.gz
RUN mv geckodriver /usr/bin
RUN chown root:root /usr/bin/geckodriver
RUN chmod +x /usr/bin/geckodriver

ARG POETRY_VERSION
RUN pip install poetry==${POETRY_VERSION}

WORKDIR /app
COPY pyproject.toml poetry.lock mypy.ini ./
# Poetry complains without a readme
RUN touch README.md
RUN poetry install --no-root

COPY src ./src
RUN poetry install

RUN mkdir /run/secrets
RUN echo "transport" > /run/secrets/db_secret

ENTRYPOINT ["poetry", "run", "python", "src/api/api/main.py"]
